name: build
on:
  push:
  pull_request:
  schedule:
    # run daily: https://crontab.cronhub.io/
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build library
        run: composer build

      - name: Check Git working tree
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Detected uncommitted changes. See status below:'
            git diff
            exit 1
          fi

      - name: Git commit and push
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          add_options: '-A'
          branch: 'feat/lib'
          commit_message: 'feat(lib): generate code'
          push_options: '--force'

      - name: Create Pull Request with GitHub CLI
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: >
          gh pr create
          --base master
          --head feat/lib
          --title 'feat(lib): generate code'
          --body ''
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
